// <auto-generated />
using System;
using Liyanjie.JsonQL.Sample.AspNetCore_2_1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Liyanjie.JsonQL.Sample.AspNetCore_2_1.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191026133921_000")]
    partial class _000
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("Liyanjie.JsonQL.Sample.AspNetCore_2_1.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreateTime");

                    b.Property<string>("Serial");

                    b.Property<int>("Status");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Liyanjie.JsonQL.Sample.AspNetCore_2_1.OrderStatusChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreateTime");

                    b.Property<Guid>("OrderId");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderStatusChanges");
                });

            modelBuilder.Entity("Liyanjie.JsonQL.Sample.AspNetCore_2_1.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreateTime");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Liyanjie.JsonQL.Sample.AspNetCore_2_1.UserAccount", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<decimal>("Coins");

                    b.Property<decimal>("Points");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("Liyanjie.JsonQL.Sample.AspNetCore_2_1.UserAccountRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Coins");

                    b.Property<DateTimeOffset>("CreateTime");

                    b.Property<decimal>("Points");

                    b.Property<string>("Remark")
                        .HasMaxLength(50);

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAccountRecords");
                });

            modelBuilder.Entity("Liyanjie.JsonQL.Sample.AspNetCore_2_1.UserProfile", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<string>("Avatar")
                        .HasMaxLength(50);

                    b.Property<string>("Nick")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Liyanjie.JsonQL.Sample.AspNetCore_2_1.Order", b =>
                {
                    b.HasOne("Liyanjie.JsonQL.Sample.AspNetCore_2_1.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Liyanjie.JsonQL.Sample.AspNetCore_2_1.OrderStatusChange", b =>
                {
                    b.HasOne("Liyanjie.JsonQL.Sample.AspNetCore_2_1.Order", "Order")
                        .WithMany("StatusChanges")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Liyanjie.JsonQL.Sample.AspNetCore_2_1.UserAccount", b =>
                {
                    b.HasOne("Liyanjie.JsonQL.Sample.AspNetCore_2_1.User", "User")
                        .WithOne("Account")
                        .HasForeignKey("Liyanjie.JsonQL.Sample.AspNetCore_2_1.UserAccount", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Liyanjie.JsonQL.Sample.AspNetCore_2_1.UserAccountRecord", b =>
                {
                    b.HasOne("Liyanjie.JsonQL.Sample.AspNetCore_2_1.User", "User")
                        .WithMany("AccountRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Liyanjie.JsonQL.Sample.AspNetCore_2_1.UserProfile", b =>
                {
                    b.HasOne("Liyanjie.JsonQL.Sample.AspNetCore_2_1.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Liyanjie.JsonQL.Sample.AspNetCore_2_1.UserProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
